### ISSUE TITLE
This project needs a finalized name

### ISSUE THREAD

**Issue by mekline** [mekline/psych-DS#3]
Mike Frank pointed out on twitter that the name "Psych-DS" obscures what's new about the project (the data specifications & standards) and suggested "Psych-Standard." 

Another issue with the name is that it implies an audience of psychologists, but in reality the standards can probably be applied to many kinds of social science data.  (Maybe this is okay? The APA style guide gets used widely, not sure if this was initially true.)

I would like to generate & consider at least a few possible options and do a vote or consensus process to choose!

**Comment by mekline** [comment]
(Feel free to add as comments here.)

**Comment by KirstieJane** [comment]
I think the two "problems" with the name are totally fair, I'll just add that I don't think they're too much of a barrier.

* I prefer `Psych-DS` over `Psych-Standard` becuase I think the "Standard" makes it sound like we're forcing people to do their experiments in a standard way which I suspect many will not like. This is not a strongly held opinion, it's a totally fine alternate name to `Psych-DS` I just prefer the "Data Standard" part of `Psych-DS`
* I don't think it's a problem to have `Psych` in the name. In fact, I think its a feature, I think it makes forking and customising the project even easier - you could imagine `Geo-DS` that is based on `Psych-DS` but is updated for geo data by the maintainers.

Neither of these are strong opinions - just adding my little :+1: to the current name!
